# ServerProperties
#指定的是这个类，servletProperties这个类.servlet这个类的类，context-path时这个类的里面的变量，所以可以
#指定项目端口号
server.port=8080
#指定项目需要添加的路径
server.servlet.context-path=/community

# ThymeleafProperties
#关闭thymeleaf的缓存，减少延缓将thymeleaf类里的cacahe从true改为false
spring.thymeleaf.cache=false
# DataSourceProperties
#连接池和数据源的配置信息
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
spring.datasource.username=root
spring.datasource.password=
#连接池的配置信息
#连接池的种类
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
#连接池的最大连接数
spring.datasource.hikari.maximum-pool-size=15
#最少的连接池保留数量
spring.datasource.hikari.minimum-idle=5
#等多久关掉连接池的连接数量
spring.datasource.hikari.idle-timeout=30000

# MybatisProperties
#mybatis的配置
#sql语句的编写位置，
mybatis.mapper-locations=classpath:mapper/*.xml
#实体类的编写位置，我们引用实体类的时候就不用包名了
mybatis.type-aliases-package=com.nowcoder.community.entity
#往MySQL数据库中插入一条记录后，可以返回该条记录的自增主键值。
mybatis.configuration.useGeneratedKeys=true
#让表中的下括号命名改为驼峰命名 。。。。。。。。。  tb_user --  tbUser
mybatis.configuration.mapUnderscoreToCamelCase=true
